# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tasks_pb2 as tasks__pb2


class TaskServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTask = channel.unary_unary(
        '/tasks.TaskService/GetTask',
        request_serializer=tasks__pb2.TaskRequest.SerializeToString,
        response_deserializer=tasks__pb2.Task.FromString,
        )
    self.ListTask = channel.unary_stream(
        '/tasks.TaskService/ListTask',
        request_serializer=tasks__pb2.TaskRequest.SerializeToString,
        response_deserializer=tasks__pb2.Task.FromString,
        )
    self.AddTask = channel.unary_unary(
        '/tasks.TaskService/AddTask',
        request_serializer=tasks__pb2.Task.SerializeToString,
        response_deserializer=tasks__pb2.TaskResponse.FromString,
        )
    self.DoneTask = channel.unary_unary(
        '/tasks.TaskService/DoneTask',
        request_serializer=tasks__pb2.Task.SerializeToString,
        response_deserializer=tasks__pb2.TaskResponse.FromString,
        )


class TaskServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DoneTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTask': grpc.unary_unary_rpc_method_handler(
          servicer.GetTask,
          request_deserializer=tasks__pb2.TaskRequest.FromString,
          response_serializer=tasks__pb2.Task.SerializeToString,
      ),
      'ListTask': grpc.unary_stream_rpc_method_handler(
          servicer.ListTask,
          request_deserializer=tasks__pb2.TaskRequest.FromString,
          response_serializer=tasks__pb2.Task.SerializeToString,
      ),
      'AddTask': grpc.unary_unary_rpc_method_handler(
          servicer.AddTask,
          request_deserializer=tasks__pb2.Task.FromString,
          response_serializer=tasks__pb2.TaskResponse.SerializeToString,
      ),
      'DoneTask': grpc.unary_unary_rpc_method_handler(
          servicer.DoneTask,
          request_deserializer=tasks__pb2.Task.FromString,
          response_serializer=tasks__pb2.TaskResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tasks.TaskService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
