# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tasks.proto',
  package='tasks',
  syntax='proto3',
  serialized_pb=_b('\n\x0btasks.proto\x12\x05tasks\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n\x0cTaskResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12(\n\x04\x64one\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1f\n\x04\x43ode\x12\x0b\n\x07SUCCEED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\"&\n\x0bTaskRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03tag\x18\x02 \x01(\t\"\xcf\x01\n\x04Task\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x18\n\x04tags\x18\x07 \x03(\x0b\x32\n.tasks.Tag\x12,\n\x08\x64ue_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x05\x61\x64\x64\x65\x64\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1f\n\x03Tag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x32\xcb\x01\n\x0bTaskService\x12,\n\x07GetTask\x12\x12.tasks.TaskRequest\x1a\x0b.tasks.Task\"\x00\x12/\n\x08ListTask\x12\x12.tasks.TaskRequest\x1a\x0b.tasks.Task\"\x00\x30\x01\x12-\n\x07\x41\x64\x64Task\x12\x0b.tasks.Task\x1a\x13.tasks.TaskResponse\"\x00\x12.\n\x08\x44oneTask\x12\x0b.tasks.Task\x1a\x13.tasks.TaskResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_TASKRESPONSE_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='tasks.TaskResponse.Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCEED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=125,
  serialized_end=156,
)
_sym_db.RegisterEnumDescriptor(_TASKRESPONSE_CODE)


_TASKRESPONSE = _descriptor.Descriptor(
  name='TaskResponse',
  full_name='tasks.TaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tasks.TaskResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done', full_name='tasks.TaskResponse.done', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASKRESPONSE_CODE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=156,
)


_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='tasks.TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='tasks.TaskRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='tasks.TaskRequest.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=196,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='tasks.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tasks.Task.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='tasks.Task.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='tasks.Task.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='tasks.Task.tags', index=3,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='due_time', full_name='tasks.Task.due_time', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='added', full_name='tasks.Task.added', index=5,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated', full_name='tasks.Task.updated', index=6,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=406,
)


_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='tasks.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tasks.Tag.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='tasks.Tag.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=439,
)

_TASKRESPONSE.fields_by_name['done'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TASKRESPONSE_CODE.containing_type = _TASKRESPONSE
_TASK.fields_by_name['tags'].message_type = _TAG
_TASK.fields_by_name['due_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TASK.fields_by_name['added'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TASK.fields_by_name['updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['TaskResponse'] = _TASKRESPONSE
DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['Tag'] = _TAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _TASKRESPONSE,
  __module__ = 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:tasks.TaskResponse)
  ))
_sym_db.RegisterMessage(TaskResponse)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _TASKREQUEST,
  __module__ = 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:tasks.TaskRequest)
  ))
_sym_db.RegisterMessage(TaskRequest)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:tasks.Task)
  ))
_sym_db.RegisterMessage(Task)

Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
  DESCRIPTOR = _TAG,
  __module__ = 'tasks_pb2'
  # @@protoc_insertion_point(class_scope:tasks.Tag)
  ))
_sym_db.RegisterMessage(Tag)



_TASKSERVICE = _descriptor.ServiceDescriptor(
  name='TaskService',
  full_name='tasks.TaskService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=442,
  serialized_end=645,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTask',
    full_name='tasks.TaskService.GetTask',
    index=0,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListTask',
    full_name='tasks.TaskService.ListTask',
    index=1,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddTask',
    full_name='tasks.TaskService.AddTask',
    index=2,
    containing_service=None,
    input_type=_TASK,
    output_type=_TASKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DoneTask',
    full_name='tasks.TaskService.DoneTask',
    index=3,
    containing_service=None,
    input_type=_TASK,
    output_type=_TASKRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKSERVICE)

DESCRIPTOR.services_by_name['TaskService'] = _TASKSERVICE

# @@protoc_insertion_point(module_scope)
